version: 1.3.3
base_install: true


# CONFIGURATION
# Configure defaults for dotbot project installation.


# ================================================
# Should standards be provided as Warp Project Rules?
# Set to true to add standards as project rules in WARP.md
# Set to false to reference standards as separate files
#
# Override this default when running project-install.ps1 by using the flag -StandardsAsWarpRules $true/$false
# ================================================
standards_as_warp_rules: true


# ================================================
# PROFILE
#
# Use this profile by default.
#
# Override this default when running project-install.ps1 by using the flag -Profile [profile-name]
# ================================================

profile: default
