version: 1.2.0
base_install: true


# CONFIGURATION
# Configure defaults for the tools you use and how dotbot should compile commands for your projects.


# ================================================
# Do you use Warp?
# Set to true to install commands in your project's .warp/commands/dotbot/ folder
# and create WARP.md with project rules
#
# Override this default when running project-install.ps1 by using the flag -WarpCommands $true/$false
# ================================================
warp_commands: true


# ================================================
# Do you use other coding tools (Cursor, Windsurf, etc.)?
# Set to true to install commands in your project's dotbot/commands/ folder
#
# Override this default when running project-install.ps1 by using the flag -DotbotCommands $true/$false
# ================================================
dotbot_commands: false


# ================================================
# Should standards be provided as Warp Project Rules?
# Set to true to add standards as project rules in WARP.md
# Set to false to reference standards as separate files
#
# Override this default when running project-install.ps1 by using the flag -StandardsAsWarpRules $true/$false
# ================================================
standards_as_warp_rules: true


# ================================================
# PROFILE
#
# Use this profile by default.
#
# Override this default when running project-install.ps1 by using the flag -Profile [profile-name]
# ================================================

profile: default
